### ISSUE TITLE
[Urgent]: GSoC 2024 updates

### ISSUE THREAD

**Issue by henrykironde** [biocommons/biocommons.github.io#7]
biocommons' idea projects are missing the required tags or sections. Please have a look at the other project lists and include this information. 
@reece

https://github.com/orgs/biocommons/projects/8/views/1
Missing
- [ ] Recommended Skills or Skills
- [ ] Expected Results: 
- [ ] Mentors:
- [ ] Expected Project Size:  (one value out of 350h, 175h, 90h)
- [ ] Difficulty: Easy / Medium /hard

**Comment by reece** [comment]
@henrykironde : I updated the projects. I hadn't seen a prescribed template. Look okay now?

**Comment by henrykironde** [comment]
Looks good to me
